name: Cypress CI para API Rest

on:
  push:
    branches: [ api-cy-github-actions ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Iniciar servidor
        run: npm start &

      - name: Aguardar servidor
        run: npx wait-on http://localhost:3000

      - name: Executar Cypress
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          browser: chrome

      - name: Publicar relatório
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report